export default class Config {
    public static showCollisionAreas: boolean = false;
    public static strokeCollisionAreas: boolean = true;
    public static fillCollisionAreas: boolean = false;
    public static pauseOnFocusLost: boolean = true;

    public static tileSize: number = 16;






    public static mapData: string =
    `FFFFFFFFFF FFFFFFFFFFFF FFFFFFFFFFFFFFFFFFFFF
FGGGGGGGGG GGGfgTT6GGGG GGGGGGGGGGFGGGGGGGGGG
FGfGGGGGGG GGGGgTT6GGGG GGGGGGGGGGFGGGGGGGGGG
FGGGGGGGGG GGGGgTT6GGGG GGGfGGGGGGFGGGfGGGGGG
FGGGGGGGGG GGGGdTTnfGGG GGGGGGGGGGFGGGGGGGGGG
FTTTTTTTTT TTTTTTTTTTTT TTTTTTTTTT4TTTTTTTTTT
FTTTTTTTTT TTTTTTTTTTTT TTTTTTTTTT4TTTTTTTTTT
Fbbbbbbbbb bbbbcTTzbbbb bbbbbbbbbbFbbbbbbbbbb
FGGGGGGGGG GGGGgTT6GGGG GGGGGGGGGGFGGGGGGGGGG
FGGGGGGfGG GGGGgTT6GGGG GGGGGGGGGGFGGGGGGGGGG
FGGGGGGGGG GGGGgTT6GGGG GGGGGfGGGGFGGGGGGGGGG
FGGGGGGGGG GGGGgTT6SGGG GGGGGGGGGGFGGGGGGGGGG
FGGG1UUIGG GGGGgTT6GGGG GGG1UUIGGGFGGGGGGGGGG
FGGGWXXPGG GGGGgTT6GGGG GGGWXXPGGGFGGGGGGGGGG
FGGGWXXPGG GGGGgTT6GGGG GGGWXXPGGGFGGGGGGGGGG
FGGGQMMLGG GGGGgTT6GGGG GGGQMMLGGGFGGGGGGGGGG
FGGGGGGGGG GGGGgTT6GGGG GGGGGGGGGGFGGGGGGGGGG
FGGGGGfGGG GGGGgTT6GGGG GGGGGGGGGGFGGGGGGGGGG
FGGGGfGGGG GGGGgTT6fGGG GGGGGGGGGGFGGGGGGGGGG
FGGGGGGGGG GGGGgTT6GGGG GGGGGGGGGGFGGGGGGGGGG
FGGGGGGGGG GGGGgTT6GGGG GGGfGGGGGGFGGGGGGGGGG
FGGGGGGGGG GGGGgTT6GGGG GGGGGGGGGGFGGGGGGGGGG
FGGfGGGGGG GGGGgTT6GGGG GGGGGGGGfGFGGGGGGGGGG
FGGGGGGGGG GGGfgTT6GGGG GGGGGGGGGGFGGGGGGGGGG
FGGGGGGGGG GGGGgTT6GGGG GGGGGGGGGGFGGGGGGGGGG
FGGGGGfGGG GGGGgTT6GGGG GGGGGGGGGGFGGGGGGGGGG
FGfGGGGGGG GGGGgTT6GfGG GGGGGGGGGGFGGGGGGGGGG
FGGGGGGGGG fGGGgTT6GGGG GGGGGGGGGGFGGGGGGGGGG
FGGGGGGGGG GGGGgTT6GGfG GGGGGGGGGGFGGGGGfGGGG
FFFFFFFFFF FFFFF44FFFFF FFFFFFFFFFFFFFFFFFFFF
FGGGGGGGGG GGGGgTT6GGGG GGGGGGGGGGFGGGGGGGGGG
FGGGGGGGGG GGGGgTT6GGGG GGGGGGGGGGFGGGGGGGGGG
FGGGGGGGGG GGGGgTT6GGGG GGGGGGGGGGFGGGGGGGGGG
FGGGGGGGGG GGGGgTT6GGGG GGGGGGGGGGFGGGGGGGGGG
FGGGGGGGGG GGGGgTT6GGGG GGGGGGGGGGFGGGGGGGGGG
FGGGGGGGGG GGGGgTT6GGGG GGGGGGGGGGFGGGGGGGGGG
FGGGGGGGGG GGGGgTT6GGGG GGGGGGGGGGFGGGGGGGGGG
FGGGGGGGGG GGGGgTT6GGGG GGGGGGGGGGFGGGGGGGGGG
FGGGGGGGGG GGGGgTT6GGGG GGGGGGGGGGFGGGGGGGGGG`;
}
